### ISSUE TITLE
Missing IFFE

### ISSUE THREAD

**Issue by markbrown4** [mtscout6/gulp-cjsx#5]
Shouldn't compiled .cjsx files be wrapped in CoffeeScript's IFFE?
```
(function() {

}).call(this);
```

**Comment by mtscout6** [comment]
That is a configurable option of coffee script. I believe that's configured through the `bare` option that can be set to false to get what you are looking for. Most of the compiler options mentioned [here](http://coffeescript.org/documentation/docs/command.html) are supported.

**Comment by markbrown4** [comment]
Ah, you're right and the default is set correctly, thanks!
The default example had `{ bare: true }` and I assumed that was just how the plugin worked.
