### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by szhu** [mtscout6/gulp-cjsx#8]
Hi, I want to enable the following options:
- concat into one file
- source map

I'm new to gulp and I'm not sure if these options are supported and if so, how to enable them. (I'd normally assume that options don't exist unless documented, except that the `bare` option seems to be used without documentation.) Can you add documentation for options?

**Comment by mtscout6** [comment]
I just forward the options to https://github.com/jsdf/coffee-react

This project is just a thin wrapper that adds the gulp glue to work with coffee-react.

**Comment by szhu** [comment]
jashkenas/coffeescript#2779 says that join support is deprecated, so no need to support that.

Source maps don't seem to work with `sourceMap: true`. Is there something I'm missing?

**Comment by mtscout6** [comment]
I don't know for sure. To be honest I haven't used CoffeeScript for more than a year and half. I've been using the Babel compiler which gives you a lot of what CoffeeScript did plus more. It's also closer to the reality of what JavaScript is and will be.

**Comment by szhu** [comment]
Babel doesn't support CoffeeScript at all though right?

**Comment by mtscout6** [comment]
No it doesn't, but I'll be honest that since switching I haven't missed CoffeeScript one bit.

**Comment by szhu** [comment]
RIP CoffeeScript
